In [6]:
import pandas as pd
import numpy as np
from copy import deepcopy

In [4]:
pwd

'/Users/mickey.poaro328/Desktop/projectB'

In [7]:
cd /Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial

/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial

In [4]:
cd /Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe

/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe

In [5]:
cd ..

/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial

In [6]:
from glob import glob

In [7]:
files = glob('recipe/*csv')
files

In [8]:
df = pd.read_csv("/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe/recipe1998.csv")
print(df.head())

年ごとにパンケーキとホットケーキの数を抽出する（月ごとに変える予定）

In [8]:
year = []
for i in range(1998,2015):
    year.append(i)

for i in year:
    df = pd.read_csv(f"/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe/recipe{i}.csv",names=["title"],usecols=[2])
    df.dropna(inplace=True)
    #datetimeじゃない形があるからそれを矯正する
    #flg_is_serial = df["登録日"].astype("str").str.isdigit()
    #print(flg_is_serial.sum())
    #df = pd.to_datetime(df.loc[~flg_is_serial, "登録日"])
    #df["登録年月"] = df["登録日"].dt.strftime("%Y%m")
    pan = df.query('title.str.contains("パンケーキ")',engine="python")
    #pan["登録年月"] = pan["登録日"].dt.strftime("%Y%m")
    pan.count()["title"]
    hot = df.query('title.str.contains("ホットケーキ")',engine="python")
   # hot["登録年月"] = hot["登録日"].dt.strftime("%Y%m")
    #hot.groupby("登録年月").count()["title"]
    print(year[i-1998],len(pan),len(hot))

1998 0 0
1999 0 0
2000 1 8
2001 18 9
2002 24 33
2003 36 105
2004 49 129
2005 34 141
2006 84 170
2007 208 447
2008 253 610
2009 345 908
2010 449 847
2011 535 703
2012 734 832
2013 1187 831
2014 997 721

In [3]:
#レシピのデータとつくれぽを結びつける
num_pan=[]
for i in year:
    print(year[i-1998])
    recipe = pd.read_csv(f"/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe/recipe{i}.csv",names=["ID","title"],usecols=[0,2])
    recipe.fillna(0)
    report = pd.read_csv(f"/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/report/report{i}.csv",names=["ID"],usecols=[0])
    report.fillna(0)
    data = pd.merge(report,recipe,how="left", on = "ID")
    pan = data.query('title.str.contains("パンケーキ",na=False)',engine="python")
    data_pan=pan.pivot_table(columns='title',aggfunc='size')
    print(data_pan.describe())

1998
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
1999
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
2000
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
2001
count    4.0
mean     2.0
std      2.0
min      1.0
25%      1.0
50%      1.0
75%      2.0
max      5.0
dtype: float64
2002
count    5.000000
mean     2.200000
std      1.095445
min      1.000000
25%      1.000000
50%      3.000000
75%      3.000000
max      3.000000
dtype: float64
2003
count    4.000000
mean     3.500000
std      3.696846
min      1.000000
25%      1.750000
50%      2.000000
75%      3.750000
max      9.000000
dtype: float64
2004
count     9.000000
mean      2.444444
std       3.244654
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max      11.000000
dtype: float64
2005
count     8.000000
mean      9.875000
std      20.760109
min       1.000000
25%       1.000000
50%       2.000000
75%       4.750000
max      61.000000
dtype: float64
2006
count    39.000000
mean      4.000000
std       6.739514
min       1.000000
25%       1.000000
50%       1.000000
75%       3.500000
max      32.000000
dtype: float64
2007
count      99.000000
mean       50.252525
std       270.253144
min         1.000000
25%         1.000000
50%         3.000000
75%         8.500000
max      2112.000000
dtype: float64
2008
count    113.000000
mean      17.557522
std       48.279680
min        1.000000
25%        1.000000
50%        3.000000
75%       13.000000
max      436.000000
dtype: float64
2009
count    159.000000
mean       7.981132
std       18.758448
min        1.000000
25%        1.000000
50%        2.000000
75%        6.500000
max      196.000000
dtype: float64
2010
count    210.000000
mean      11.571429
std       42.819161
min        1.000000
25%        1.000000
50%        2.000000
75%        6.000000
max      483.000000
dtype: float64
2011
count     259.000000
mean       20.405405
std        92.278909
min         1.000000
25%         1.000000
50%         3.000000
75%         7.500000
max      1275.000000
dtype: float64
2012
count     375.000000
mean       20.490667
std       132.725640
min         1.000000
25%         1.000000
50%         2.000000
75%         7.000000
max      2395.000000
dtype: float64
2013
count    554.000000
mean       8.740072
std       26.860317
min        1.000000
25%        1.000000
50%        2.000000
75%        6.000000
max      372.000000
dtype: float64
2014
count    320.000000
mean       3.312500
std        6.896628
min        1.000000
25%        1.000000
50%        1.000000
75%        3.000000
max       71.000000
dtype: float64

In [10]:
#レシピのデータとつくれぽを結びつける
for i in year:
    print(year[i-1998])
    recipe = pd.read_csv(f"/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/recipe/recipe{i}.csv",names=["ID","title"],usecols=[0,2])
    recipe.fillna(0)
    report = pd.read_csv(f"/Users/mickey.poaro328/Desktop/projectB/SDMprojectMaterial/report/report{i}.csv",names=["ID"],usecols=[0])
    report.fillna(0)
    data = pd.merge(report,recipe,how="left", on = "ID")
    hot = data.query('title.str.contains("ホットケーキ",na=False)',engine="python")
    data_hot=hot.pivot_table(columns='title',aggfunc='size')
    print(data_hot.describe())

1998
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
1999
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
dtype: float64
2000
count    3.000000
mean     1.333333
std      0.577350
min      1.000000
25%      1.000000
50%      1.000000
75%      1.500000
max      2.000000
dtype: float64
2001
count    1.0
mean     8.0
std      NaN
min      8.0
25%      8.0
50%      8.0
75%      8.0
max      8.0
dtype: float64
2002
count    11.000000
mean      9.909091
std      19.253335
min       1.000000
25%       2.000000
50%       3.000000
75%       7.500000
max      67.000000
dtype: float64
2003
count     34.000000
mean      24.411765
std       80.416385
min        1.000000
25%        1.000000
50%        4.000000
75%       13.000000
max      470.000000
dtype: float64
2004
count    51.000000
mean      7.745098
std      10.758891
min       1.000000
25%       1.500000
50%       3.000000
75%       9.000000
max      52.000000
dtype: float64
2005
count     54.000000
mean      22.777778
std       83.921047
min        1.000000
25%        1.000000
50%        2.000000
75%        7.750000
max      581.000000
dtype: float64
2006
count     113.000000
mean       32.619469
std       121.520818
min         1.000000
25%         1.000000
50%         3.000000
75%        18.000000
max      1062.000000
dtype: float64
2007
count     281.000000
mean       25.395018
std       109.814895
min         1.000000
25%         2.000000
50%         3.000000
75%        10.000000
max      1633.000000
dtype: float64
2008
count     397.000000
mean       38.118388
std       291.700957
min         1.000000
25%         2.000000
50%         4.000000
75%        15.000000
max      5640.000000
dtype: float64
2009
count     538.000000
mean       32.970260
std       188.143995
min         1.000000
25%         2.000000
50%         4.000000
75%        14.000000
max      3902.000000
dtype: float64
2010
count     472.000000
mean       15.688559
std        75.145509
min         1.000000
25%         1.000000
50%         3.000000
75%         7.000000
max      1441.000000
dtype: float64
2011
count    375.000000
mean      20.298667
std       60.808337
min        1.000000
25%        1.000000
50%        3.000000
75%       11.000000
max      717.000000
dtype: float64
2012
count     480.000000
mean       13.872917
std        60.523590
min         1.000000
25%         1.000000
50%         3.000000
75%         7.000000
max      1091.000000
dtype: float64
2013
count    463.000000
mean      11.719222
std       43.115357
min        1.000000
25%        1.000000
50%        3.000000
75%        8.000000
max      603.000000
dtype: float64
2014
count    327.000000
mean       5.314985
std        9.296176
min        1.000000
25%        1.000000
50%        2.000000
75%        5.000000
max       76.000000
dtype: float64